# Building Modules

In [1]:
import pandas as pd

In [32]:
import risk_kit as erk

In [16]:
erk

<module 'risk_kit' from '/Users/nicholasflores/Documents/GitHub/data-science-python/finance-ml/risk_kit.py'>

In [9]:
%load_ext autoreload

In [17]:
erk.get_ffm_returns

<function risk_kit.get_ffm_returns()>

In [23]:
returns = erk.get_ffm_returns()

/Users/nicholasflores/Documents/GitHub/data-science-python/finance-ml/risk_kit.py:24: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  me_m = pd.read_csv("finance-ml-data/Portfolios_Formed_on_ME_monthly_EW.csv",


In [24]:
returns.head()

SmallCap  LargeCap
1926-07   -0.0145    0.0329
1926-08    0.0512    0.0370
1926-09    0.0093    0.0067
1926-10   -0.0484   -0.0243
1926-11   -0.0078    0.0270

In [26]:
erk.drawdown(returns['SmallCap'])['Drawdowns'].min()

-0.8330007793945303

## Deviations from Normality

In [93]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [94]:
%autoreload 2

In [50]:
hfi = erk.get_hfi_returns()

/Users/nicholasflores/Documents/GitHub/data-science-python/finance-ml/risk_kit.py:40: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.


In [51]:
hfi.head()

Convertible Arbitrage  CTA Global  Distressed Securities  \
date                                                                
1997-01                 0.0119      0.0393                 0.0178   
1997-02                 0.0123      0.0298                 0.0122   
1997-03                 0.0078     -0.0021                -0.0012   
1997-04                 0.0086     -0.0170                 0.0030   
1997-05                 0.0156     -0.0015                 0.0233   

         Emerging Markets  Equity Market Neutral  Event Driven  \
date                                                             
1997-01            0.0791                 0.0189        0.0213   
1997-02            0.0525                 0.0101        0.0084   
1997-03           -0.0120                 0.0016       -0.0023   
1997-04            0.0119                 0.0119       -0.0005   
1997-05            0.0315                 0.0189        0.0346   

         Fixed Income Arbitrage  Global Macro  Long/Short Equity  \
date                                                               
1997-01                  0.0191        0.0573             0.0281   
1997-02                  0.0122        0.0175            -0.0006   
1997-03                  0.0109       -0.0119            -0.0084   
1997-04                  0.0130        0.0172             0.0084   
1997-05                  0.0118        0.0108             0.0394   

         Merger Arbitrage  Relative Value  Short Selling  Funds Of Funds  
date                                                                      
1997-01            0.0150          0.0180        -0.0166          0.0317  
1997-02            0.0034          0.0118         0.0426          0.0106  
1997-03            0.0060          0.0010         0.0778         -0.0077  
1997-04           -0.0001          0.0122        -0.0129          0.0009  
1997-05            0.0197          0.0173        -0.0737          0.0275

In [52]:
hfi.columns

Index(['Convertible Arbitrage', 'CTA Global', 'Distressed Securities',
       'Emerging Markets', 'Equity Market Neutral', 'Event Driven',
       'Fixed Income Arbitrage', 'Global Macro', 'Long/Short Equity',
       'Merger Arbitrage', 'Relative Value', 'Short Selling',
       'Funds Of Funds'],
      dtype='object')

In [53]:
## If median return is less than the mean return, you have negative skewed returns. 
## As median is a measure of how often an event happens.

In [54]:
pd.concat([hfi.mean(),hfi.median(),hfi.mean()>hfi.median()], axis="columns")

0       1      2
Convertible Arbitrage   0.005508  0.0065  False
CTA Global              0.004074  0.0014   True
Distressed Securities   0.006946  0.0089  False
Emerging Markets        0.006253  0.0096  False
Equity Market Neutral   0.004498  0.0051  False
Event Driven            0.006344  0.0084  False
Fixed Income Arbitrage  0.004365  0.0055  False
Global Macro            0.005403  0.0038   True
Long/Short Equity       0.006331  0.0079  False
Merger Arbitrage        0.005356  0.0060  False
Relative Value          0.005792  0.0067  False
Short Selling          -0.001701 -0.0053   True
Funds Of Funds          0.004262  0.0052  False

$$
\text{Skewness} = \frac{\frac{1}{N} \sum_{i=1}^{N} (X_i - \bar{X})^3}{\left(\frac{1}{N} \sum_{i=1}^{N} (X_i - \bar{X})^2\right)^{3/2}}
$$

$$
\text{Skewness} = \frac{\frac{1}{N} \sum_{i=1}^{N} (X_i - \bar{X})^3}{(\text{Var}(X))^{3/2}}
$$


In [58]:
erk.skewness(hfi).sort_values()

Fixed Income Arbitrage   -3.940320
Convertible Arbitrage    -2.639592
Equity Market Neutral    -2.124435
Relative Value           -1.815470
Event Driven             -1.409154
Merger Arbitrage         -1.320083
Distressed Securities    -1.300842
Emerging Markets         -1.167067
Long/Short Equity        -0.390227
Funds Of Funds           -0.361783
CTA Global                0.173699
Short Selling             0.767975
Global Macro              0.982922
dtype: float64

In [59]:
import scipy.stats

In [60]:
scipy.stats.skew(hfi)

array([-2.63959223,  0.17369864, -1.30084204, -1.16706749, -2.12443538,
       -1.40915356, -3.94032029,  0.98292188, -0.39022677, -1.32008333,
       -1.81546975,  0.76797484, -0.36178308])

In [61]:
erk.skewness(hfi)

Convertible Arbitrage    -2.639592
CTA Global                0.173699
Distressed Securities    -1.300842
Emerging Markets         -1.167067
Equity Market Neutral    -2.124435
Event Driven             -1.409154
Fixed Income Arbitrage   -3.940320
Global Macro              0.982922
Long/Short Equity        -0.390227
Merger Arbitrage         -1.320083
Relative Value           -1.815470
Short Selling             0.767975
Funds Of Funds           -0.361783
dtype: float64

In [62]:
import numpy as np

In [63]:
hfi.shape

(263, 13)

In [70]:
normal_rets = np.random.normal(0,.15,size=(263000,1))

In [71]:
erk.skewness(normal_rets)

0.004450023210993525

## Kurtosis

In [75]:
erk.kurtosis(normal_rets)

3.012904359488879

In [76]:
erk.kurtosis(hfi)

Convertible Arbitrage     23.280834
CTA Global                 2.952960
Distressed Securities      7.889983
Emerging Markets           9.250788
Equity Market Neutral     17.218555
Event Driven               8.035828
Fixed Income Arbitrage    29.842199
Global Macro               5.741679
Long/Short Equity          4.523893
Merger Arbitrage           8.738950
Relative Value            12.121208
Short Selling              6.117772
Funds Of Funds             7.070153
dtype: float64

In [78]:
scipy.stats.kurtosis(normal_rets)

array([0.01290436])

In [77]:
scipy.stats.kurtosis(hfi)

array([20.28083446, -0.04703963,  4.88998336,  6.25078841, 14.21855526,
        5.03582817, 26.84219928,  2.74167945,  1.52389258,  5.73894979,
        9.12120787,  3.11777175,  4.07015278])

In [79]:
scipy.stats.jarque_bera(normal_rets)

SignificanceResult(statistic=2.6928276331103587, pvalue=0.2601716127784964)

In [80]:
scipy.stats.jarque_bera(hfi)

SignificanceResult(statistic=25656.585999171337, pvalue=0.0)

In [95]:
erk.is_normal(normal_rets)

True

In [96]:
erk.is_normal(hfi)

False

In [99]:
hfi.aggregate(erk.is_normal)

Convertible Arbitrage     False
CTA Global                 True
Distressed Securities     False
Emerging Markets          False
Equity Market Neutral     False
Event Driven              False
Fixed Income Arbitrage    False
Global Macro              False
Long/Short Equity         False
Merger Arbitrage          False
Relative Value            False
Short Selling             False
Funds Of Funds            False
dtype: bool

In [102]:
ffme = erk.get_ffm_returns()

/Users/nicholasflores/Documents/GitHub/data-science-python/finance-ml/risk_kit.py:25: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  header=0,


In [104]:
erk.skewness(ffme)

SmallCap    4.410739
LargeCap    0.233445
dtype: float64

In [105]:
erk.kurtosis(ffme)

SmallCap    46.845008
LargeCap    10.694654
dtype: float64

In [106]:
erk.is_normal(ffme)

False

In [108]:
ffme.aggregate(erk.is_normal)

SmallCap    False
LargeCap    False
dtype: bool